name: Ticket Central Sync

on:
  workflow_dispatch:
    inputs:
      initFromNow:
        description: "Skip all history for new sources (true/false)"
        required: false
        default: "false"
      chunkRows:
        description: "Rows to scan per source per run"
        required: false
        default: "800"
      timeBudgetSec:
        description: "Seconds per run before safe exit"
        required: false
        default: "330"
  schedule:
    # frequent small runs = reliable continuation
    - cron: "*/10 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install gspread==6.1.4 google-auth==2.35.0
      - name: Run sync
        env:
          GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}
          MASTER_SPREADSHEET_ID: ${{ secrets.MASTER_SPREADSHEET_ID }}
          MASTER_TICKETS_TAB: ${{ vars.MASTER_TICKETS_TAB || 'Tickets' }}
          MASTER_SOURCE_TAB:  ${{ vars.MASTER_SOURCE_TAB  || 'Source'  }}
          __MARKERS_TAB_NAME: ${{ vars.MARKERS_TAB_NAME   || '__Markers' }}
          INIT_FROM_NOW: ${{ github.event.inputs.initFromNow || 'false' }}
          CHUNK_ROWS: ${{ github.event.inputs.chunkRows || '800' }}
          TIME_BUDGET_SEC: ${{ github.event.inputs.timeBudgetSec || '330' }}
          THROTTLE_MS: ${{ vars.THROTTLE_MS || '200' }}
          MAX_SOURCES_PER_RUN: ${{ vars.MAX_SOURCES_PER_RUN || '15' }}
        run: |
          python sync.py
